[package]
name = "config-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.18"
serde = { version = "1.0.228", features = ["derive"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


